### ISSUE TITLE
Email for token does not arrive

### ISSUE THREAD

**Issue by MaxPlay066** [DeepGenX/CodeGenX#12]
Hi! I'm sorry, but the mail for the verification doesn't arrive. I checked, the mail is perfectly writed. Why that?

**Comment by Aryagm** [comment]
Hi,

I just tested the system, the token system seems to work fine. Could you try again? Maybe try to check your spam/promotion folders.

Let me know if it works

Thanks,

**Comment by MaxPlay066** [comment]
Nothing, i tried again, and checked all the categories (Spam, promotion, inbox and more), but nothing, no mail arrived.

**Comment by Aryagm** [comment]
Hmm, that is strange. Nothing seems to be wrong with the system (people are signing up). If possible could you share your email? I can check if it has already been used, and share the token with you if that's the case. You can also try with another email if you have one.

Thanks,

**Comment by MaxPlay066** [comment]
Hey, i founded out that (maybe only for me) it only works on mozilla firefox. Now i got the Token. Thanks for the support!

**Comment by Aryagm** [comment]
Oh, that is great! 

May I know which browser you were working with earlier, so I can try to figure out the issue.

Thanks,

**Comment by KingZumbie** [comment]
Having the same problem here. I've done all the steps but the email verification does NOT arrive at my email. I also checked my email and saw nothing at all.

**Comment by tereshchuk-dev** [comment]
Similar problem. No confirmation email :(

**Comment by MaxPlay066** [comment]
What browser are you both using?

Il Sab 30 Lug 2022, 22:23 Michael Tereshchuk ***@***.***> ha
scritto:
