### ISSUE TITLE
plugin support for PyCharm

### ISSUE THREAD

**Issue by jtydhr88** [DeepGenX/CodeGenX#13]
Hi guys,
I am so excited to see such a project!
As an IDE developer, I would like to contribute a PyCharm plugin(open source) to support it.
Here is the repo:
https://github.com/jtydhr88/codegenx-pycharm-plugin

For some quick views, I took some screenshots:
1. Settings
![settings](https://user-images.githubusercontent.com/860985/143976776-72017338-0adc-4c67-9748-860e6bd784a7.png)
2. Tool window
![toolwindow](https://user-images.githubusercontent.com/860985/143976799-e1b7d803-aec5-4288-8753-fb1ecc3c72c8.png)
3. Generate code
![generatecode](https://user-images.githubusercontent.com/860985/143976806-4890841d-420f-4fc6-ad11-31ce8504f28d.png)
4. Insert code
![insertcode](https://user-images.githubusercontent.com/860985/143976815-1b0a0495-04ed-440f-b550-5f074dc9aeb3.png)

Please let me know if you are interested in it and we can discuss more.

**Comment by Aryagm** [comment]
Hi,
This looks amazing! Creating a plugin for PyCharm was one of the top priorities on our todo.
We will definitely work on making a official version. 

Are you available on Discord, by any chance? We do our development there and it would be easier to communicate.

Thanks,

**Comment by jtydhr88** [comment]
You can add me by the name, terryjia, in Discord

**Comment by Aryagm** [comment]
Hi, 

I will need your id which can be found in the bottom-left corner:
![image](https://user-images.githubusercontent.com/80019072/144072592-8e66d00c-9134-48f2-b864-b59396ab9142.png)

Thanks,

**Comment by jtydhr88** [comment]
oh, this is TerryJia#2431
