### ISSUE TITLE
How do I see ALL generated code?

### ISSUE THREAD

**Issue by UniqueName12345** [DeepGenX/CodeGenX#15]
I have seen this extension from your reddit post, and I want to try it out. What is the keyboard combination to see all the code that AI generated?

**Comment by Matthias1590** [comment]
You can press Ctrl+D to get suggestions

**Comment by UniqueName12345** [comment]
..i only see 1 suggestion?

**Comment by Matthias1590** [comment]
In that case the model only suggested 1 piece of code, if you're trying to get better results you can have a look at [the docs](https://docs.deepgenx.com/most_out/) to see how to write better prompts
