### ISSUE TITLE
is the finetuned gpt-j-6B model open source？

### ISSUE THREAD

**Issue by cdj0311** [DeepGenX/CodeGenX#17]
i just found gpt-j-6B model, the finetuned model have open source?

**Comment by Aryagm** [comment]
Hi,

Yes the fine-tuned model is open source!

You can find the weights to the model here: https://drive.google.com/drive/folders/1FCFLw2Svp7s8bcW6TZB83P_iwVUn2ITo?usp=sharing

Thanks,
Arya

**Comment by cdj0311** [comment]
> https://drive.google.com/drive/folders/1FCFLw2Svp7s8bcW6TZB83P_iwVUn2ITo?usp=sharing

Thanks！
