### ISSUE TITLE
Can't get API key.

### ISSUE THREAD

**Issue by robertoioi** [DeepGenX/CodeGenX#19]
Hi, I write there cause I didn't find any contact form in your website. No email arrived, tried with different addresses and browser. Thanks.

**Comment by Aryagm** [comment]
Hi,

There seemed to be a small problem with our servers so the emails were not being sent.

We fixed the issue and should work now. Could you please try again and let us know if it works?

Thanks,
Arya

**Comment by robertoioi** [comment]
It works, confirmed.
Thanks,
Roberto

**Comment by Aryagm** [comment]
That's great!

Thanks for letting us know about the issue!

**Comment by SpinnySpiwal** [comment]
i am now getting the same issue.

**Comment by smart2pet** [comment]
Please fastly fix it
