### ISSUE TITLE
Request of API key 

### ISSUE THREAD

**Issue by AlbertFlorinus** [DeepGenX/CodeGenX#22]
I've requested an API key by submitting my email, I've been looking everywhere but it doesn't seem to send any verification link (gmail).

**Comment by Aryagm** [comment]
Hi,

Sorry for the late response.

We were having some issues with our servers a couple of days ago. The problem is now fixed.

Could you please try again and let me know if it works?

Thanks,
Arya

**Comment by AlbertFlorinus** [comment]
@Aryagm
It's working now, thanks!

**Comment by smart2pet** [comment]
But I cant get the key now.It was happened again.
