### ISSUE TITLE
word.replaceAll is not a function

### ISSUE THREAD

**Issue by CharlesChiuGit** [DeepGenX/CodeGenX#23]
After pressing `Ctrl + D`, vscode retures a error meassage says "word.replaceAll is not a function".
Is there any tips on how to get CodeGenX works properly?

I'm just using the example code from CodeGenX's doc, and my cursor is at the end of the comment.
```python
def new_text_file(filename, content):
    """Create a new text file and add content to it"""
```

**Comment by Aryagm** [comment]
Hi @charleschiu2012 ,

I am not able to replicate the issue. 

Could you please let me know which version of Visual Studio Code you are using?

Thanks and Regards,
Arya Manjaramkar

**Comment by charleschiu2012** [comment]
@Aryagm Hi, I'm using vscode 1.65.2 version on Win10, here's a screenshot of it:
![image](https://user-images.githubusercontent.com/32497323/157963247-8266a26d-132e-4998-ae98-d97620e7c498.png)
---
Another screenshot of the error:
![image](https://user-images.githubusercontent.com/32497323/157964356-02fa4db0-5e41-4d24-b27e-405f09342824.png)

**Comment by Aryagm** [comment]
Hi,

Is the issue still persisting?

Thanks,
Arya Manjaramkar

**Comment by charliie-dev** [comment]
Sorry, I stop using this extension. I will close this issue.
