### ISSUE TITLE
Migration Error after April 4th

### ISSUE THREAD

**Issue by GrahamboJangles** [DeepGenX/CodeGenX#24]
When I press Ctrl + D the output says 
`We are currently in the process of migrating CodeGenX to more powerful hardware. This will improve inference time and make the service a lot faster. CodeGenX will be temporarily inactive from the 28th of March 2022 for about one week. The code generation will not work and new users won't be able to sign up during this period. The new hardware will also allow us to start working on a new and improved version of CodeGenX with more accurate generation capabilities! We apologize for the inconvinience.`

A week after the 28th of March would be April 4th. Is it still down nearly a month later or is there something wrong with my setup?

**Comment by pbgo2** [comment]
has exactly same issues, not possible to get API key on https://www.deepgenx.com/signin

**Comment by Aryagm** [comment]
Hey Guys,

Sorry for the late response.

We are actually having some compatibility issues with the new TPU V-4's.

We have raised an issue and the guys at google are investigating the cause of the problem.

We are trying our best to get the service online as quickly as possible.

Sorry for the inconvenience.

Thanks and Regards,
Arya Manjaramkar
