### ISSUE TITLE
When the API would be available again?

### ISSUE THREAD

**Issue by nashid** [DeepGenX/CodeGenX#27]
Wondering when the API would be available again?

Any tentative timeline in mind?

**Comment by Aryagm** [comment]
Hi Nashid,

CodeGenX is finally online again! 🎉

If you are an existing user you will need to update the extension in VsCode. If you are new you can get your API token on our [website](https://deepgenx.com).

Sorry for the long wait.

Thanks and Regards,
Arya Manjaramkar
